### ISSUE TITLE
on firefox the cookie accept thing doesnt automatically disappear

### ISSUE THREAD

**Issue by ghost** [Shifty-The-Dev/RedditVideoGenerator#18]
![obraz](https://user-images.githubusercontent.com/93012064/230733762-afe4af39-ced9-4178-bfb6-d6f532a52042.png)
the image explains everything

**Comment by Om3gaOfficial** [comment]
Same problem here...

**Comment by ghost** [comment]
> Same problem here...
> 

I have found a workaround for this, click accept all but then the notification thing also pops up and makes the entire screen go darker
