### ISSUE TITLE
voiceover file can't be found

### ISSUE THREAD

**Issue by yeetus1992** [Shifty-The-Dev/RedditVideoGenerator#2]
(noob) when I try to run the code, it gives the following error:

> raise IOError(("MoviePy error: the file %s could not be found!\n"
OSError: MoviePy error: the file Voiceovers/2023-02-20-116opqc-title.mp3 could not be found!
Please check that you entered the correct path.

I already installed dependencies, created a copy of config.ini and modified VLCPath, OutputDirectory and BackgroundDirectory. I'd be more than grateful for help.

**Comment by PinkQween** [comment]
Did you find the error?
